# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bftbl',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('version', models.IntegerField(db_column='Version')),
            ],
            options={
                'db_table': 'bftbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domaintbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('version', models.IntegerField(db_column='Version')),
            ],
            options={
                'db_table': 'domaintbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dombf',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dombf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proctbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('process', models.CharField(db_column='Process', max_length=100)),
                ('complexity', models.CharField(blank=True, max_length=100, null=True)),
                ('criticality', models.CharField(blank=True, max_length=100, null=True)),
                ('responsible_program', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'proctbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subproctbl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('subprocess', models.CharField(db_column='subProcess', max_length=100)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('resapplmodule', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'subproctbl',
                'managed': False,
            },
        ),
    ]
